require('dotenv').config();
const express = require('express');
const cors = require('cors');

const app = express();
app.use(cors({ origin: '*' }));
app.use(express.json());

const API_KEY = process.env.GETGEMS_API_KEY;
const COLLECTION_ADDR = process.env.COLLECTION_ADDRESS;
// URL для API v2 (REST)
const API_URL = 'https://api.getgems.io/graphql'; 

app.post('/api/mint', async (req, res) => {
  const { userAddress } = req.body;

  if (!userAddress || !API_KEY || !COLLECTION_ADDR) {
    return res.status(400).json({ error: 'Missing config' });
  }

  try {
    // Используем GraphQL мутацию для минта cNFT
    // Примечание: Для работы этого метода у вас должен быть баланс TON на кошельке, 
    // привязанном к API ключу, для оплаты газа создания NFT.
    const query = `
      mutation MintCnft($input: MintCnftInput!) {
        mintCnft(input: $input) {
          ok
          nftItem {
            address
          }
        }
      }
    `;

    const variables = {
      input: {
        collectionAddress: COLLECTION_ADDR,
        ownerAddress: userAddress,
        metadata: {
          name: `TG Gift #${Math.floor(Math.random() * 10000)}`,
          description: "Generated by TG Giftverse",
          image: "https://api.dicebear.com/9.x/glass/svg?seed=" + userAddress
        }
      }
    };

    const response = await fetch(API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${API_KEY}`,
        'X-API-Key': API_KEY
      },
      body: JSON.stringify({ query, variables })
    });

    const result = await response.json();

    if (result.errors) {
      console.error('GetGems API Error:', JSON.stringify(result.errors));
      return res.status(500).json({ error: 'API Error', details: result.errors });
    }

    const nftAddress = result.data?.mintCnft?.nftItem?.address;
    
    if (!nftAddress) {
       return res.status(500).json({ error: 'No NFT address returned' });
    }

    res.json({ success: true, nftAddress });

  } catch (error) {
    console.error('Server Crash:', error);
    res.status(500).json({ error: 'Internal Error' });
  }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Backend running on ${PORT}`));
